export * from './EuroTechLogo';

// Re-export modern Lucide icons (just like DiscoverKarabakh)
export {
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  User as UserIcon,
  Users as UsersIcon,
  UserPlus as UserPlusIcon,
  FileText as FileTextIcon,
  CheckCircle2 as CheckCircleIcon,
  AlertCircle as AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Plus as PlusIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  ArrowLeft as ArrowLeftIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  Shield as ShieldIcon,
  ShieldCheck as ShieldCheckIcon,
  CreditCard as CreditCardIcon,
  Briefcase as BriefcaseIcon,
  Building2 as BuildingIcon,
  LogOut as LogoutIcon,
  X as CloseIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Link2 as LinkIcon,
  Send as SendIcon,
  Trash2 as TrashIcon,
  Plane as PlaneIcon,
  Globe as GlobeIcon,
  FileCheck as FileCheckIcon,
  ExternalLink as ExternalLinkIcon,
  BadgeCheck as BadgeCheckIcon,
  Receipt as ReceiptIcon,
} from 'lucide-react';
