module.exports = {
  DEFAULT_LANGUAGE: 'az',
  SUPPORTED_LANGUAGES: ['az', 'en', 'ru'],
  SERVICE_PRICES: {
    PREMIUM_LOUNGE: 81.0,
    FILE_PREPARATION: 55.0,
    TRAVEL_INSURANCE: 35.0,
    HOTEL_BOOKING: 15.0,
    FLIGHT_BOOKING: 15.0,
    FORM_ASSIST: 24.0,
    COURIER: 20.0,
    BIOMETRIC_PHOTO: 12.0,
    EXPRESS_PROCESSING: 60.0,
    TRANSLATION_APOSTILLE: 45.0,
  },
  PORTAL_SERVICE_FEES: {
    INDIVIDUAL: 120.0,
    GROUP_AGENT: 90.0,
    CORPORATE: 150.0,
  },
};
