module.exports = {
  DEFAULT_LANGUAGE: 'az',
  SUPPORTED_LANGUAGES: ['az', 'en', 'ru'],
  SERVICE_PRICES: {
    EXPRESS_PROCESSING: 60.0,
    TRAVEL_INSURANCE: 35.0,
    TRANSLATION_APOSTILLE: 45.0,
    COURIER: 25.0,
    FLIGHT_BOOKING: 20.0,
    HOTEL_BOOKING: 25.0,
  },
  PORTAL_SERVICE_FEES: {
    INDIVIDUAL: 120.0,
    GROUP_AGENT: 90.0,
    CORPORATE: 150.0,
  },
};
