require('dotenv').config();

module.exports = {
  PORT: process.env.PORT || 5000,
  NODE_ENV: process.env.NODE_ENV || 'development',
  DATABASE_URL: process.env.DATABASE_URL || 'mysql://root:@localhost:3306/eurotech_db',
  JWT_SECRET: process.env.JWT_SECRET || 'eurotech_super_secret_jwt_key_2026_safe_and_secure',
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '7d',
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY || 'sk_test_mock_eurotech_stripe_key',
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET || 'whsec_mock_eurotech_webhook_secret',
  SMTP_HOST: process.env.SMTP_HOST || 'smtp.mailtrap.io',
  SMTP_PORT: process.env.SMTP_PORT || 2525,
  SMTP_USER: process.env.SMTP_USER || '',
  SMTP_PASS: process.env.SMTP_PASS || '',
  SMTP_FROM: process.env.SMTP_FROM || 'EuroTech Services <noreply@eurotech.services>',
  UPLOAD_DIR: process.env.UPLOAD_DIR || './uploads',
  ARCHIVE_DIR: process.env.ARCHIVE_DIR || './archives',
  STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY || 'pk_test_mock_eurotech_key',
  LOCAL_BANK_MERCHANT_ID: process.env.LOCAL_BANK_MERCHANT_ID || 'EUROTECH_MERCHANT_01',
  LOCAL_BANK_TERMINAL_ID: process.env.LOCAL_BANK_TERMINAL_ID || 'EUROTECH_TERM_01',
  LOCAL_BANK_SECRET_KEY: process.env.LOCAL_BANK_SECRET_KEY || 'local_bank_super_secret_mac_key_2026',
  LOCAL_BANK_GATEWAY_URL: process.env.LOCAL_BANK_GATEWAY_URL || 'https://bank-gateway.eurotech.services/pay',
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY || '',
  META_WHATSAPP_TOKEN: process.env.META_WHATSAPP_TOKEN || '',
  META_WHATSAPP_PHONE_ID: process.env.META_WHATSAPP_PHONE_ID || '108823928192831',
  META_WHATSAPP_BUSINESS_ACCOUNT_ID: process.env.META_WHATSAPP_BUSINESS_ACCOUNT_ID || '992838192831023',
  META_WHATSAPP_WEBHOOK_VERIFY_TOKEN: process.env.META_WHATSAPP_WEBHOOK_VERIFY_TOKEN || 'eurotech_wa_verify_token_2026',
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID || '',
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN || '',
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER || '+15005550006',
  BULKSMS_AZ_API_KEY: process.env.BULKSMS_AZ_API_KEY || '',
  STORAGE_DRIVER: process.env.STORAGE_DRIVER || 'local', // 'local' or 's3'
  S3_ENDPOINT: process.env.S3_ENDPOINT || 'http://localhost:9000',
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME || 'eurotech-documents',
  S3_REGION: process.env.S3_REGION || 'eu-central-1',
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID || 'minioadmin',
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY || 'minioadmin',
};

