const ROLES = {
  INDIVIDUAL: 'INDIVIDUAL',
  AGENT_TUR_OPERATOR: 'AGENT_TUR_OPERATOR',
  CORPORATE_HR: 'CORPORATE_HR',
  OPERATOR: 'OPERATOR',
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN',
};

const PERMISSIONS = {
  VIEW_METRICS: ['OPERATOR', 'MANAGER', 'ADMIN'],
  REVIEW_DOCUMENTS: ['OPERATOR', 'MANAGER', 'ADMIN'],
  CHANGE_DOSSIER_STATUS: ['OPERATOR', 'MANAGER', 'ADMIN'],
  MANAGE_USERS: ['ADMIN'],
};

module.exports = {
  ROLES,
  PERMISSIONS,
};
