module.exports = {
  PASSPORT_RETENTION_DAYS: parseInt(process.env.PASSPORT_RETENTION_DAYS || '30', 10),
  APPLICATION_RETENTION_DAYS: parseInt(process.env.APPLICATION_RETENTION_DAYS || '365', 10),
  AUDIT_RETENTION_DAYS: parseInt(process.env.AUDIT_RETENTION_DAYS || '1095', 10), // 3 years
  FINANCIAL_RETENTION_DAYS: parseInt(process.env.FINANCIAL_RETENTION_DAYS || '2555', 10), // 7 years
  DATA_CLASSIFICATIONS: {
    PUBLIC: 'PUBLIC',
    INTERNAL: 'INTERNAL',
    CONFIDENTIAL: 'CONFIDENTIAL',
    PII: 'PII',
    SENSITIVE_PII: 'SENSITIVE_PII',
    BIOMETRIC: 'BIOMETRIC',
    FINANCIAL: 'FINANCIAL',
  },
};
